name: Compile Spark

on:
  pull_request:
    branches: [ master, develop, feature/* ]
  push:
    branches: [master]
  schedule:
   - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  windows:
    name: run on windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1.4.1
    - name: compile
      run: | 
        cl mdns.c /Zi /Fdmdns.pdb /link /out:mdns.exe ws2_32.lib iphlpapi.lib
    - name: upload executable
      uses: actions/upload-artifact@v2
      with:
        name: windows
        path: |
          mdns.exe
  # mac-and-ubuntu:
  #   runs-on: ${{matrix.os}}
  #   strategy:
  #     matrix:
  #       os: [macos-latest, ubuntu-latest]
  #   name: ${{matrix.os}}
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: compile
  #       run: |
  #         g++ -std=c++17 main.cpp -o spark
  #     - name: run
  #       run: |
  #         ./spark test.spark
  #       shell: bash
  #     - name: upload executable
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: ${{matrix.os}}
  #         path: |
  #           spark
  